# 🤖 J-Quants Interactive Analyst

セッションベースの対話型分析環境です。
- `Session` = 1つの分析テーマ（スイング、マクロなど）
- 会話・計算結果は全てディスクに永続化されます
- カーネル再起動後も `Session("同じ名前")` で完全復元されます

In [1]:
import sys
from pathlib import Path

project_root = Path("..").resolve()
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from dotenv import load_dotenv
load_dotenv(project_root / ".env")

# マジックコマンド %%chat を有効化
%load_ext src.agent.magic

## セッションの作成（または再開）

新規の場合は `data_range` を指定します。再開する場合は名前だけでOKです。

In [2]:
from src.agent.session import Session

# 新規セッション（データを読み込む）
session = Session(
    name="swing_20240515",
    data_range=("2024-05-15", "2024-05-15"),
    data_dir=str(project_root / "data"),
)

# 翌日の再開時はこれだけ:
# session = Session("swing_20240515", data_dir=str(project_root / "data"))

print(f"Session: {session.name}")
print(f"Data: {len(session.df)} rows")
print(f"Artifacts: {session.list_artifacts()}")

INFO:src.agent.core:Using model: gemini-2.5-flash
INFO:src.analyzer.runner:Loading 1 files...
INFO:src.agent.session:Session 'swing_20240515': Loaded 4359 records (2024-05-15 ~ 2024-05-15)

Session: swing_20240515
Data: 4359 rows
Artifacts: []

## AIとの対話

`%%chat` で日本語の指示を送るだけです。AIはデータの状態を常に把握しています。

In [3]:
%%chat
今日読み込んでいるデータの中で、終値が始値よりも5%以上高い銘柄（大きな陽線）を探して、出来高の多い順に並べてください。

*(**swing_20240515** が考え中...)*

INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent "HTTP/1.1 200 OK"
INFO:src.agent.session:Saved artifact: step_001.parquet (57 rows)

**🤖 swing_20240515**:

```python
# 終値が始値よりも5%以上高い銘柄をフィルタリング
condition = (df['AdjC'] / df['AdjO']) >= 1.05
output_df = df[condition]

# 出来高の多い順に並べ替え
output_df = output_df.sort_values(by='AdjVo', ascending=False)

# 結果の考察
if not output_df.empty:
    result = f"本日、終値が始値より5%以上高かった銘柄は {len(output_df)} 件ありました。\n" \
             f"特に出来高が多かった上位5銘柄は以下の通りです:\n" \
             f"{output_df[['Date', 'Code', 'AdjO', 'AdjC', 'AdjVo']].head().to_string(index=False)}"
else:
    result = "本日、終値が始値より5%以上高い銘柄は見つかりませんでした。"
```

---

✅ **実行完了**

> 本日、終値が始値より5%以上高かった銘柄は 57 件ありました。
特に出来高が多かった上位5銘柄は以下の通りです:
      Date  Code   AdjO   AdjC      AdjVo
2024-05-15 65740   12.0   13.8 84420000.0
2024-05-15 67400   18.0   19.0 22318800.0
2024-05-15 52160  252.0  328.0 16841600.0
2024-05-15 77710   95.0  103.0 11492400.0
2024-05-15 15180 1078.0 1136.0  8897500.0

,Date,Code,O,H,L,C,UL,LL,Vo,Va,AdjFactor,AdjO,AdjH,AdjL,AdjC,AdjVo
2740,2024-05-15,65740,1204.0,1384.0,1113.0,1384.0,1,0,844200.0,1.066995e+09,1.0,12.0,13.8,11.1,13.8,84420000.0
2823,2024-05-15,67400,18.0,19.0,18.0,19.0,0,0,22318800.0,4.036973e+08,1.0,18.0,19.0,18.0,19.0,22318800.0
2102,2024-05-15,52160,252.0,332.0,248.0,328.0,1,0,16841600.0,5.105079e+09,1.0,252.0,332.0,248.0,328.0,16841600.0
3405,2024-05-15,77710,95.0,107.0,92.0,103.0,1,0,11492400.0,1.183465e+09,1.0,95.0,107.0,92.0,103.0,11492400.0
128,2024-05-15,15180,5390.0,6210.0,5390.0,5680.0,0,0,1779500.0,1.020472e+10,1.0,1078.0,1242.0,1078.0,1136.0,8897500.0
1571,2024-05-15,41830,4455.0,4777.0,4389.0,4715.0,0,0,2765400.0,1.271678e+10,1.0,2227.5,2388.5,2194.5,2357.5,5530800.0
3996,2024-05-15,92270,1200.0,1320.0,1200.0,1290.0,0,0,2924300.0,3.738118e+09,1.0,1200.0,1320.0,1200.0,1290.0,2924300.0
1813,2024-05-15,45640,15.0,16.0,15.0,16.0,0,0,2861900.0,4.344950e+07,1.0,15.0,16.0,15.0,16.0,2861900.0
979,2024-05-15,31030,215.0,234.0,213.0,231.0,0,0,2635100.0,5.994758e+08,1.0,215.0,234.0,213.0,231.0,2635100.0
3714,2024-05-15,83460,338.0,370.0,338.0,359.0,0,0,2466500.0,8.795353e+08,1.0,338.0,370.0,338.0,359.0,2466500.0
689,2024-05-15,25850,5500.0,5900.0,5370.0,5790.0,0,0,510400.0,2.883771e+09,1.0,1375.0,1475.0,1342.5,1447.5,2041600.0
3393,2024-05-15,77410,17870.0,19325.0,17870.0,19280.0,0,0,1944600.0,3.638585e+10,1.0,17870.0,19325.0,17870.0,19280.0,1944600.0
317,2024-05-15,18600,1022.0,1126.5,995.6,1112.0,0,0,1861300.0,2.027989e+09,1.0,1022.0,1126.5,995.6,1112.0,1861300.0
2578,2024-05-15,63300,885.0,1034.0,865.0,1034.0,1,0,1822400.0,1.771948e+09,1.0,885.0,1034.0,865.0,1034.0,1822400.0
1112,2024-05-15,33500,31.0,33.0,30.0,33.0,0,0,1419400.0,4.487000e+07,1.0,31.0,33.0,30.0,33.0,1419400.0
3357,2024-05-15,76890,716.0,851.0,686.0,851.0,1,0,1403000.0,1.131961e+09,1.0,716.0,851.0,686.0,851.0,1403000.0
4034,2024-05-15,92740,748.0,805.0,748.0,794.0,0,0,1242900.0,9.765941e+08,1.0,748.0,805.0,748.0,794.0,1242900.0
1026,2024-05-15,31820,1168.0,1335.0,1150.0,1317.0,0,0,1170500.0,1.501985e+09,1.0,1168.0,1335.0,1150.0,1317.0,1170500.0
2201,2024-05-15,55350,2713.0,2921.0,2713.0,2882.0,0,0,142500.0,4.065344e+08,1.0,339.1,365.1,339.1,360.3,1140000.0
2234,2024-05-15,56020,4330.0,4630.0,4260.0,4575.0,0,0,137700.0,6.190030e+08,1.0,866.0,926.0,852.0,915.0,688500.0
3031,2024-05-15,70940,1400.0,1610.0,1346.0,1500.0,0,0,688200.0,1.047404e+09,1.0,1400.0,1610.0,1346.0,1500.0,688200.0
2317,2024-05-15,58920,1916.0,2119.0,1830.0,2098.0,0,0,670300.0,1.352887e+09,1.0,1916.0,2119.0,1830.0,2098.0,670300.0
3029,2024-05-15,70920,1094.0,1186.0,1093.0,1169.0,0,0,480000.0,5.562254e+08,1.0,1094.0,1186.0,1093.0,1169.0,480000.0
1132,2024-05-15,33930,1454.0,1593.0,1381.0,1593.0,0,0,454700.0,6.730196e+08,1.0,1454.0,1593.0,1381.0,1593.0,454700.0
1346,2024-05-15,37790,135.0,155.0,134.0,143.0,0,0,378800.0,5.514440e+07,1.0,135.0,155.0,134.0,143.0,378800.0
2048,2024-05-15,50330,926.0,1054.0,926.0,1005.0,0,0,357400.0,3.579499e+08,1.0,926.0,1054.0,926.0,1005.0,357400.0
288,2024-05-15,18050,1370.0,1455.0,1346.0,1448.0,0,0,348600.0,4.923847e+08,1.0,1370.0,1455.0,1346.0,1448.0,348600.0
65,2024-05-15,142A0,2795.0,3185.0,2768.0,3155.0,0,0,161100.0,4.808215e+08,1.0,1397.5,1592.5,1384.0,1577.5,322200.0
1940,2024-05-15,48110,2126.0,2285.0,2072.0,2267.0,0,0,89500.0,1.983154e+08,1.0,708.7,761.7,690.7,755.7,268500.0
1210,2024-05-15,35120,430.0,487.0,427.0,455.0,0,0,243400.0,1.121512e+08,1.0,430.0,487.0,427.0,455.0,243400.0
2341,2024-05-15,59400,85.0,92.0,85.0,92.0,0,0,2424300.0,2.125256e+08,1.0,850.0,920.0,850.0,920.0,242430.0
1699,2024-05-15,43930,4050.0,4560.0,4050.0,4450.0,0,0,213800.0,9.355740e+08,1.0,4050.0,4560.0,4050.0,4450.0,213800.0
1397,2024-05-15,38960,490.0,525.0,489.0,515.0,0,0,212300.0,1.077587e+08,1.0,490.0,525.0,489.0,515.0,212300.0
1230,2024-05-15,35510,765.0,834.0,735.0,810.0,0,0,211000.0,1.699788e+08,1.0,765.0,834.0,735.0,810.0,211000.0
1695,2024-05-15,43890,1260.0,1384.0,1204.0,1369.0,0,0,99400.0,1.303178e+08,1.0,630.0,692.0,602.0,684.5,198800.0
2503,2024-05-15,62080,1523.0,1637.0,1505.0,1621.0,0,0,197100.0,3.137063e+08,1.0,1523.0,1637.0,1505.0,1621.0,197100.0
3962,2024-05-15,91580,1625.0,1755.0,1616.0,1735.0,0,0,156900.0,2.686517e+08,1.0,1625.0,1755.0,1616.0,1735.0,156900.0
1568,2024-05-15,41790,308.0,339.0,307.0,331.0,0,0,131800.0,4.273860e+07,1.0,308.0,339.0,307.0,331.0,131800.0
2595,2024-05-15,63510,3790.0,4110.0,3770.0,4095.0,0,0,60100.0,2.400440e+08,1.0,1895.0,2055.0,1885.0,2047.5,120200.0
2546,2024-05-15,62780,4810.0,5210.0,4785.0,5110.0,0,0,117700.0,5.900565e+08,1.0,4810.0,5210.0,4785.0,5110.0,117700.0
1556,2024-05-15,41670,389.0,413.0,375.0,413.0,0,0,98400.0,3.842420e+07,1.0,389.0,413.0,375.0,413.0,98400.0
2757,2024-05-15,66140,1949.0,2160.0,1935.0,2047.0,0,0,86100.0,1.757931e+08,1.0,1949.0,2160.0,1935.0,2047.0,86100.0
2585,2024-05-15,63370,2111.0,2259.0,2111.0,2217.0,0,0,80800.0,1.782764e+08,1.0,2111.0,2259.0,2111.0,2217.0,80800.0
2765,2024-05-15,66260,1910.0,2035.0,1910.0,2027.0,0,0,70200.0,1.380702e+08,1.0,1910.0,2035.0,1910.0,2027.0,70200.0
3820,2024-05-15,88360,17.0,18.0,17.0,18.0,0,0,65500.0,1.160000e+06,1.0,17.0,18.0,17.0,18.0,65500.0
4031,2024-05-15,92710,430.0,455.0,417.0,452.0,0,0,52100.0,2.313340e+07,1.0,430.0,455.0,417.0,452.0,52100.0
269,2024-05-15,17730,117.0,125.0,114.0,125.0,0,0,258000.0,3.114300e+07,1.0,585.0,625.0,570.0,625.0,51600.0
2389,2024-05-15,60260,7130.0,8680.0,7130.0,8680.0,1,0,43200.0,3.617240e+08,1.0,7130.0,8680.0,7130.0,8680.0,43200.0
3404,2024-05-15,77690,3460.0,3815.0,3410.0,3770.0,0,0,34400.0,1.264375e+08,1.0,3460.0,3815.0,3410.0,3770.0,34400.0
1524,2024-05-15,40730,690.0,750.0,688.0,750.0,0,0,33000.0,2.395680e+07,1.0,690.0,750.0,688.0,750.0,33000.0
234,2024-05-15,16930,6879.0,7618.0,6879.0,7439.0,0,0,32970.0,2.340342e+08,1.0,6879.0,7618.0,6879.0,7439.0,32970.0
812,2024-05-15,28130,3715.0,4415.0,3570.0,4415.0,1,0,26100.0,1.012765e+08,1.0,3715.0,4415.0,3570.0,4415.0,26100.0
3007,2024-05-15,70670,1005.0,1100.0,1000.0,1067.0,0,0,24000.0,2.532520e+07,1.0,1005.0,1100.0,1000.0,1067.0,24000.0
2345,2024-05-15,59450,1750.0,1851.0,1750.0,1850.0,0,0,18700.0,3.340010e+07,1.0,1750.0,1851.0,1750.0,1850.0,18700.0
3056,2024-05-15,71310,1670.0,1770.0,1662.0,1763.0,0,0,10200.0,1.741140e+07,1.0,1670.0,1770.0,1662.0,1763.0,10200.0
3673,2024-05-15,82250,3260.0,3480.0,3115.0,3480.0,0,0,6400.0,2.127500e+07,1.0,3260.0,3480.0,3115.0,3480.0,6400.0
1521,2024-05-15,40690,1119.0,1191.0,1119.0,1175.0,0,0,2400.0,2.800100e+06,1.0,1119.0,1191.0,1119.0,1175.0,2400.0

## 深掘り（AIは前回の結果を知っている）

In [4]:
%%chat
その結果の中から、さらに終値が2000円以下の銘柄だけに絞り込んで。

*(**swing_20240515** が考え中...)*

INFO:google_genai.models:AFC is enabled with max remote calls: 10.
INFO:httpx:HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent "HTTP/1.1 200 OK"
INFO:src.agent.session:Saved artifact: step_002.parquet (43 rows)

**🤖 swing_20240515**:

```python
# 前回の結果 (output_df) から、終値が2000円以下の銘柄をフィルタリング
condition = output_df['AdjC'] <= 2000
output_df = output_df[condition]

# 結果の考察
if not output_df.empty:
    result = f"終値が始値より5%以上高く、かつ終値が2000円以下だった銘柄は {len(output_df)} 件ありました。\n" \
             f"特に出来高が多かった上位5銘柄は以下の通りです:\n" \
             f"{output_df[['Date', 'Code', 'AdjO', 'AdjC', 'AdjVo']].head().to_string(index=False)}"
else:
    result = "終値が始値より5%以上高く、かつ終値が2000円以下の銘柄は見つかりませんでした。"
```

---

✅ **実行完了**

> 終値が始値より5%以上高く、かつ終値が2000円以下だった銘柄は 43 件ありました。
特に出来高が多かった上位5銘柄は以下の通りです:
      Date  Code   AdjO   AdjC      AdjVo
2024-05-15 65740   12.0   13.8 84420000.0
2024-05-15 67400   18.0   19.0 22318800.0
2024-05-15 52160  252.0  328.0 16841600.0
2024-05-15 77710   95.0  103.0 11492400.0
2024-05-15 15180 1078.0 1136.0  8897500.0

,Date,Code,O,H,L,C,UL,LL,Vo,Va,AdjFactor,AdjO,AdjH,AdjL,AdjC,AdjVo
2740,2024-05-15,65740,1204.0,1384.0,1113.0,1384.0,1,0,844200.0,1.066995e+09,1.0,12.0,13.8,11.1,13.8,84420000.0
2823,2024-05-15,67400,18.0,19.0,18.0,19.0,0,0,22318800.0,4.036973e+08,1.0,18.0,19.0,18.0,19.0,22318800.0
2102,2024-05-15,52160,252.0,332.0,248.0,328.0,1,0,16841600.0,5.105079e+09,1.0,252.0,332.0,248.0,328.0,16841600.0
3405,2024-05-15,77710,95.0,107.0,92.0,103.0,1,0,11492400.0,1.183465e+09,1.0,95.0,107.0,92.0,103.0,11492400.0
128,2024-05-15,15180,5390.0,6210.0,5390.0,5680.0,0,0,1779500.0,1.020472e+10,1.0,1078.0,1242.0,1078.0,1136.0,8897500.0
3996,2024-05-15,92270,1200.0,1320.0,1200.0,1290.0,0,0,2924300.0,3.738118e+09,1.0,1200.0,1320.0,1200.0,1290.0,2924300.0
1813,2024-05-15,45640,15.0,16.0,15.0,16.0,0,0,2861900.0,4.344950e+07,1.0,15.0,16.0,15.0,16.0,2861900.0
979,2024-05-15,31030,215.0,234.0,213.0,231.0,0,0,2635100.0,5.994758e+08,1.0,215.0,234.0,213.0,231.0,2635100.0
3714,2024-05-15,83460,338.0,370.0,338.0,359.0,0,0,2466500.0,8.795353e+08,1.0,338.0,370.0,338.0,359.0,2466500.0
689,2024-05-15,25850,5500.0,5900.0,5370.0,5790.0,0,0,510400.0,2.883771e+09,1.0,1375.0,1475.0,1342.5,1447.5,2041600.0
317,2024-05-15,18600,1022.0,1126.5,995.6,1112.0,0,0,1861300.0,2.027989e+09,1.0,1022.0,1126.5,995.6,1112.0,1861300.0
2578,2024-05-15,63300,885.0,1034.0,865.0,1034.0,1,0,1822400.0,1.771948e+09,1.0,885.0,1034.0,865.0,1034.0,1822400.0
1112,2024-05-15,33500,31.0,33.0,30.0,33.0,0,0,1419400.0,4.487000e+07,1.0,31.0,33.0,30.0,33.0,1419400.0
3357,2024-05-15,76890,716.0,851.0,686.0,851.0,1,0,1403000.0,1.131961e+09,1.0,716.0,851.0,686.0,851.0,1403000.0
4034,2024-05-15,92740,748.0,805.0,748.0,794.0,0,0,1242900.0,9.765941e+08,1.0,748.0,805.0,748.0,794.0,1242900.0
1026,2024-05-15,31820,1168.0,1335.0,1150.0,1317.0,0,0,1170500.0,1.501985e+09,1.0,1168.0,1335.0,1150.0,1317.0,1170500.0
2201,2024-05-15,55350,2713.0,2921.0,2713.0,2882.0,0,0,142500.0,4.065344e+08,1.0,339.1,365.1,339.1,360.3,1140000.0
2234,2024-05-15,56020,4330.0,4630.0,4260.0,4575.0,0,0,137700.0,6.190030e+08,1.0,866.0,926.0,852.0,915.0,688500.0
3031,2024-05-15,70940,1400.0,1610.0,1346.0,1500.0,0,0,688200.0,1.047404e+09,1.0,1400.0,1610.0,1346.0,1500.0,688200.0
3029,2024-05-15,70920,1094.0,1186.0,1093.0,1169.0,0,0,480000.0,5.562254e+08,1.0,1094.0,1186.0,1093.0,1169.0,480000.0
1132,2024-05-15,33930,1454.0,1593.0,1381.0,1593.0,0,0,454700.0,6.730196e+08,1.0,1454.0,1593.0,1381.0,1593.0,454700.0
1346,2024-05-15,37790,135.0,155.0,134.0,143.0,0,0,378800.0,5.514440e+07,1.0,135.0,155.0,134.0,143.0,378800.0
2048,2024-05-15,50330,926.0,1054.0,926.0,1005.0,0,0,357400.0,3.579499e+08,1.0,926.0,1054.0,926.0,1005.0,357400.0
288,2024-05-15,18050,1370.0,1455.0,1346.0,1448.0,0,0,348600.0,4.923847e+08,1.0,1370.0,1455.0,1346.0,1448.0,348600.0
65,2024-05-15,142A0,2795.0,3185.0,2768.0,3155.0,0,0,161100.0,4.808215e+08,1.0,1397.5,1592.5,1384.0,1577.5,322200.0
1940,2024-05-15,48110,2126.0,2285.0,2072.0,2267.0,0,0,89500.0,1.983154e+08,1.0,708.7,761.7,690.7,755.7,268500.0
1210,2024-05-15,35120,430.0,487.0,427.0,455.0,0,0,243400.0,1.121512e+08,1.0,430.0,487.0,427.0,455.0,243400.0
2341,2024-05-15,59400,85.0,92.0,85.0,92.0,0,0,2424300.0,2.125256e+08,1.0,850.0,920.0,850.0,920.0,242430.0
1397,2024-05-15,38960,490.0,525.0,489.0,515.0,0,0,212300.0,1.077587e+08,1.0,490.0,525.0,489.0,515.0,212300.0
1230,2024-05-15,35510,765.0,834.0,735.0,810.0,0,0,211000.0,1.699788e+08,1.0,765.0,834.0,735.0,810.0,211000.0
1695,2024-05-15,43890,1260.0,1384.0,1204.0,1369.0,0,0,99400.0,1.303178e+08,1.0,630.0,692.0,602.0,684.5,198800.0
2503,2024-05-15,62080,1523.0,1637.0,1505.0,1621.0,0,0,197100.0,3.137063e+08,1.0,1523.0,1637.0,1505.0,1621.0,197100.0
3962,2024-05-15,91580,1625.0,1755.0,1616.0,1735.0,0,0,156900.0,2.686517e+08,1.0,1625.0,1755.0,1616.0,1735.0,156900.0
1568,2024-05-15,41790,308.0,339.0,307.0,331.0,0,0,131800.0,4.273860e+07,1.0,308.0,339.0,307.0,331.0,131800.0
1556,2024-05-15,41670,389.0,413.0,375.0,413.0,0,0,98400.0,3.842420e+07,1.0,389.0,413.0,375.0,413.0,98400.0
3820,2024-05-15,88360,17.0,18.0,17.0,18.0,0,0,65500.0,1.160000e+06,1.0,17.0,18.0,17.0,18.0,65500.0
4031,2024-05-15,92710,430.0,455.0,417.0,452.0,0,0,52100.0,2.313340e+07,1.0,430.0,455.0,417.0,452.0,52100.0
269,2024-05-15,17730,117.0,125.0,114.0,125.0,0,0,258000.0,3.114300e+07,1.0,585.0,625.0,570.0,625.0,51600.0
1524,2024-05-15,40730,690.0,750.0,688.0,750.0,0,0,33000.0,2.395680e+07,1.0,690.0,750.0,688.0,750.0,33000.0
3007,2024-05-15,70670,1005.0,1100.0,1000.0,1067.0,0,0,24000.0,2.532520e+07,1.0,1005.0,1100.0,1000.0,1067.0,24000.0
2345,2024-05-15,59450,1750.0,1851.0,1750.0,1850.0,0,0,18700.0,3.340010e+07,1.0,1750.0,1851.0,1750.0,1850.0,18700.0
3056,2024-05-15,71310,1670.0,1770.0,1662.0,1763.0,0,0,10200.0,1.741140e+07,1.0,1670.0,1770.0,1662.0,1763.0,10200.0
1521,2024-05-15,40690,1119.0,1191.0,1119.0,1175.0,0,0,2400.0,2.800100e+06,1.0,1119.0,1191.0,1119.0,1175.0,2400.0

## 自分のコードで計算結果を操作する

In [5]:
# AIが計算した最新の output_df を自分で操作できる
if session.latest_output_df is not None:
    print(session.latest_output_df.describe())
else:
    print("まだ計算結果はありません。")

                      Date            O            H            L  \
count                   43    43.000000    43.000000    43.000000
mean   2024-05-15 00:00:00  1181.697674  1299.453488  1163.269767
min    2024-05-15 00:00:00    15.000000    16.000000    15.000000
25%    2024-05-15 00:00:00   323.000000   354.500000   322.500000
50%    2024-05-15 00:00:00   926.000000  1054.000000   926.000000
75%    2024-05-15 00:00:00  1427.000000  1601.500000  1363.500000
max    2024-05-15 00:00:00  5500.000000  6210.000000  5390.000000
std                    NaN  1288.311825  1418.451532  1272.739234

                 C            Vo            Va  AdjFactor         AdjO  \
count    43.000000  4.300000e+01  4.300000e+01       43.0    43.000000
mean   1270.209302  1.885377e+06  9.303498e+08        1.0   770.565116
min      16.000000  2.400000e+03  1.160000e+06        1.0    12.000000
25%     345.000000  1.347500e+05  4.415975e+07        1.0   338.550000
50%    1034.000000  3.574000e+05  3.579499e+08        1.0   748.000000
75%    1546.500000  1.599450e+06  1.011999e+09        1.0  1143.500000
max    5790.000000  2.231880e+07  1.020472e+10        1.0  1750.000000
std    1363.278778  4.408232e+06  1.787502e+09        0.0   517.690430

              AdjH         AdjL         AdjC         AdjVo
count    43.000000    43.000000    43.000000  4.300000e+01
mean    845.897674   759.325581   831.053488  4.020831e+06
min      13.800000    11.100000    13.800000  2.400000e+03
25%     367.550000   338.550000   359.650000  1.770000e+05
50%     834.000000   735.000000   810.000000  3.788000e+05
75%    1281.000000  1134.500000  1232.500000  1.841850e+06
max    1851.000000  1750.000000  1850.000000  8.442000e+07
std     563.204314   511.212344   554.760868  1.334147e+07

## 保存された計算結果（artifacts）の確認

In [ ]:
# 各ステップの結果はParquetとして永続化されている
print("Saved artifacts:", session.list_artifacts())

# 過去のステップの結果を呼び出すこともできる
# df_step1 = session.load_artifact(1)